//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDevelopment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiteEntities : DbContext
    {
        public SiteEntities()
            : base("name=SiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Seasons> Seasons { get; set; }
        public virtual DbSet<Standings> Standings { get; set; }
        public virtual DbSet<Teams> Teams { get; set; }
    }
}
