//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        public int MatchesID { get; set; }
        public int HomeTeamID { get; set; }
        public int AwayTeamID { get; set; }
        public int HomeTeamScore { get; set; }
        public int AwayTeamScore { get; set; }
        public TypeOfWin Result { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Teams AwayTeam { get; set; }
        public virtual Teams HomeTeam { get; set; }
    }
}
