//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteDevelopment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Standings
    {
        public Nullable<int> TeamID { get; set; }
        public int StandingsID { get; set; }
        public int SeasonsID { get; set; }
        public int GamesPlayed { get; set; }
        public int Wins { get; set; }
        public int Losses { get; set; }
        public int OT { get; set; }
        public int Points { get; set; }
        public int ROW { get; set; }
        public int GoalsFor { get; set; }
        public int GoalsAgainst { get; set; }
        public int GoalDifferential { get; set; }
        public int HomeWins { get; set; }
        public int HomeLosses { get; set; }
        public int HomeOT { get; set; }
        public int AwayWins { get; set; }
        public int AwayLosses { get; set; }
        public int AwayOT { get; set; }
        public int ShootoutWins { get; set; }
        public int ShootoutLosses { get; set; }
        public int LastWins { get; set; }
        public int LastLosses { get; set; }
        public int LastOT { get; set; }
        public int Streak { get; set; }
    
        public virtual Seasons Seasons { get; set; }
        public virtual Teams Team { get; set; }
    }
}
